### ISSUE TITLE
Wildcard expansion not supported in Windows Powershell?

### ISSUE THREAD

**Issue by mipoon** [frapa/sampan#1]
Hello.  First, I would like to say that I really appreciate you writing this version of the panorama eoi fix for Samsung jpgs.  I just tried running the sampan exe in Windows 11 using Powershell and although Powershell is supposed to support wilcard expansion, it does not work.  I get the following error:

PS C:\temp> .\sampan pans\*.jpg -i
thread 'main' panicked at 'Cannot open file pans\*.jpg: Os { code: 123, kind: Other, message: "The filename, directory name, or volume label syntax is incorrect." }', src/main.rs:124:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I am, however, able to get wildcard expansion to work using git bash.  Thanks!

**Comment by frapa** [comment]
Hi @mipoon,

Thanks for trying the program out! The problem is that Powershell does not expand wildcards like all normal shells, but passes the * character to the program. 

Could you try running:

```powershell
sampan (get-item pans*.jpg) -i
```

And report if that works?

**Comment by mipoon** [comment]
Yes, that works!  That's fantastic.  Thank you so much for the quick solution.

I have another question/issue but will open a separate ticket for that so it is not confused.

**Comment by frapa** [comment]
@mipoon I updated the README with instructions. Thanks for testing!
